charmed-kubernetes/charm-containerd

reactive/containerd.py

Suggested improvement to https://github.com/charmed-kubernetes/charm-containerd/pull/10.
If we get an exception where we do expect it (LXD), then don't block, and don't bother retrying.
If we get an exception where we don't expect it, then don't block, but do retry.
I've tested this with cs:~cynerva/containerd-2. Confirmed that br_netfilter is still loading correctly on non-LXD, and that it fails gracefully without blocking on LXD.

Don't block on br_netfilter

---

reactive/containerd.py

Fixes https://bugs.launchpad.net/charm-containerd/+bug/1834524 in stable.
Previously reviewed in https://github.com/charmed-kubernetes/charm-containerd/pull/10.

[stable] Don't block on br_netfilter

---

layer.yaml
metadata.yaml
reactive/containerd.py
templates/config.toml

Bring Docker Registry charm support to Containerd.  Most of the code couldn't be shared between Docker and Containerd due to the differing ways they configure external registries.

Docker registry support

---

reactive/containerd.py

Addressing https://bugs.launchpad.net/charm-containerd/+bug/1837710
Make sure we clean all remnants of Nvidia drivers when departing.
Tested with stable CK 1.15 and Docker charm.

Be better at cleaning up on depart

---

README.md
reactive/containerd.py

Changed charm to override http_proxy values with juju-http(s)-proxy values. 
[#LP1831712](https://bugs.launchpad.net/charm-kubernetes-master/+bug/1831712)

Change charms to use juju-http{s}-proxy model settings

---

reactive/containerd.py

An issue was uncovered where after nvidia drivers install
the charm does not remove it's 'maintenance' state.
This resolves that by calling config_changed.

Add config_changed call after drivers install

---

wheelhouse.txt

This charm was depending on requests but did not install it in its venv. Due to the previous default for `include_system_packages` of `true`, it was previously relying on the system-wide version. That default changed recently so it's now necessary to include it in the wheelhouse. It's also safer to do so.

Add missing charm requirement: requests

---

templates/config.toml

Fixes https://bugs.launchpad.net/charm-containerd/+bug/1851850
This error:
```
failed to resolve image "172.16.0.239:5000/pause-amd64:3.1": parse registry endpoint "172.16.0.239:5000": parse 172.16.0.239:5000: first path segment in URL cannot contain colon
```
occurs because the configured mirror endpoint does not include the `https://` scheme like it's supposed to.
We could fix this by adding `https://` to the endpoint config, but actually, the mirror entry in the file seems to serve no purpose -- if the registry is `172.16.0.239:5000`, and there's no mirror defined for it, then it's going to connect to `https://172.16.0.239:5000` anyway.

Fix private registry URL parse error

---

reactive/containerd.py

Had an issue when deploying this charm in an environment with proxies. Using this patch I was able to resolve it.
https://bugs.launchpad.net/charm-containerd/+bug/1850862

Add support for proxies when downloading nvidia drivers

---

.travis.yml
lib/charms/layer/containerd.py
reactive/containerd.py
tests/test_containerd_lib.py
tox.ini

Fixing LP1865543 by using the `@atexit` decorator to ensure the charm's
status is always set.
In line with other charms, enabling the flake8-docstrings tests to
ensure they are enforced.

Fixing LP1865543 and adding docstrings flake8 test

---

actions/upgrade-containerd
reactive/containerd.py

Re-organising code so that the alive test for containerd can also be
used to get the server version.  Use this to set juju's application
version.
Hold containerd apt package once installed to stop unwanted creep.
Tidy-up upgrade-containerd run-action and make sure it resets juju
application version.

LP1866040 charm should set the application version

---

layer.yaml
reactive/containerd.py

Fixes [lp 1873477](https://bugs.launchpad.net/charm-containerd/+bug/1873477) and a concern from [layer-container-runtime-common](https://github.com/charmed-kubernetes/layer-container-runtime-common/pull/7#pullrequestreview-395475069).
This PR adds a new `containerd.restart` flag that can be used to restart the containerd service.  This consolidates multiple `host.service_restart` calls into one place, and it also allows other layers to set this flag if they have modified the system in a way that warrants a containerd restart.
Note: I switched over to `layer:status` instead of `hookenv.status_set` because the former will give precedent to blocked > maint > active status messages.  This prevents us from losing a blocked message from a base layer if the charm layer were to …

new containerd restart handler

---

reactive/containerd.py
tests/conftest.py
tests/test_containerd_lib.py
tests/test_containerd_reactive.py
tox.ini

We can't actually pause the service because the series upgrade hooks run on the subordinates before the principal so doing so could interfere with the pod drain process. So instead, we just set a status to let the Juju admin know that it's ok to proceed.
Part of https://bugs.launchpad.net/charm-containerd/+bug/1869944

Add support for series upgrade

---

reactive/containerd.py
tests/test_containerd_reactive.py

Addressing https://bugs.launchpad.net/charm-containerd/+bug/1874910
Needed to facilitate `update-status` to periodically check for changes to the Juju model configuration and apply them if necessary.
Tested on CK 1.18 stable with just juju config, just charm config and both together.

New event to periodically check for juju model config changes

---

reactive/containerd.py

Fixes https://bugs.launchpad.net/charm-containerd/+bug/1883663
Tested on CK 1.18 with breakpoints in `_juju_proxy_changed` to check values on startup and when changing proxy values

Cache after proxy merge instead of before

---

reactive/containerd.py

The filename for `.ca/.key/.cert` files is based on registry URL.
If it starts with `https://` then `open()` hits `FileNotFoundError`,
and the config-changed hook fails.
Fix this by stripping the URL for the filename as for the `host` field.
Before:
```
$ juju config containerd custom_registries='[{"url": "https://example.com", "ca_file": "'"$(base64 -w 0 < ca.crt)"'"}]'
$ juju status | grep containerd
containerd         1.3.3    error        1  containerd         jujucharms   94  ubuntu
containerd/0*       error     idle            10.191.59.168          hook failed: "config-changed"
$ juju ssh containerd/0 'tail /var/log/juju/unit-containerd-*.log'
...
2020-11-06 18:49:27 WARNING config-changed   File "/var/lib/juju/agents/unit-containerd-0/charm/reactive/containerd.py", line 151, in …
```

LP1900881 Strip registry URL for filenames as for the host field

---

reactive/containerd.py
tests/test_containerd_reactive.py

Upon config changes to the `custom_registries` option, any TLS files
of registries which are no longer in the new config are left behind.
So, check if `custom_registries` changed; if so remove the TLS files
of the old registries.  New registries have TLS files written anyway.
(If it has not changed, no files are removed.)
Note, this does not remove TLS files other than the previous config
(eg, left behind by older versions of the charm, or manually stored.)
Before:
```
$ echo test >file
$ juju config containerd custom_registries='[{"url": "registry-one", "ca_file": "'$(base64 <file)'", "key_file": "'$(base64 <file)'", "cert_file": "'$(base64 <file)'"}]'
$ juju ssh containerd/0 'ls -1 /etc/containerd/'
config.toml
registry-one.ca
registry-one.cert
registry-one.key
Connection to …
```

 LP1901050 Remove TLS files of old custom_registries

---

config.yaml
reactive/containerd.py

it turns out the README on this was a LITTLE confusing because `base64 < file.pem` can result in a multiline file.  When juju sees this without the correct quoting, it can't see that the config is ALL one single string input.  
the important bit here
```bash
juju config containerd custom_registries='[{
... 
"ca_file": "'"$(base64 -w 0 < ~/my.custom.ca.pem)"'"
...
}]'
```
this says create a string that had the right json format right up the `"ca_file": "` bit, then append some text that's the output of a command `base64 < ~/my.custom.ca.pem` which could be multi-line text so we'll wrap that in double-quotes then append more text so we need another `'`  and then close that base64 string with a close quote `"`

Improve README and config description around custom_registries

---

tests/unit/test_containerd_lib.py
tests/unit/test_containerd_reactive.py

The charms.unit_test library was updated to include better support for unitdata, removing the need to treat unitdata as a mock.

Fix unit tests to work with new unitdata support

---

README.md
config.yaml
reactive/containerd.py
templates/config_v2.toml

These changes are added to be able to support the nvidia gpu operator: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html
The detailed bug/feature request can be found in [LP:#1938055](https://bugs.launchpad.net/charm-containerd/+bug/1938055)
The nvidia gpu operator only supports the v2 config of containerd

Add support for containerd v2 config

---

.github/workflows/main.yaml
reactive/containerd.py
tests/data/bundle.yaml
tests/integration/test_containerd_integration.py
tox.ini

Updates integration tests to inspect the containerd config pre and post addition of a second container registry.

Test that containerd config toml generates under integration tests

---

reactive/containerd.py
templates/config.toml
templates/config_v2.toml
tests/data/bundle.yaml
tests/integration/test_containerd_integration.py
tests/unit/test_containerd_reactive.py
tests/unit/test_custom_registries_render/v1_config.toml
tests/unit/test_custom_registries_render/v2_config.toml
tox.ini

Use unit testing to verify that:
* templates render appropriate v1 and v2 `config.toml`
* adjust template config spacing so generated configs look nicer
* remove deprecated registry 'auths' section with `registry.configs."<url>".auth` instead

Test templates match expected v1 and v2 rendered configs

---

config.yaml

https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
[LP#1971831](https://bugs.launchpad.net/charm-containerd/+bug/)

update nvidia apt key urls to match upstream

---

.github/workflows/main.yaml
actions/upgrade-actions.py
reactive/containerd.py
tests/unit/test_containerd_reactive.py

Change behaviour to where a change in nvidia_apt_key_urls does not trigger a full reinstall of nvidia_apt_packages. Partial fix to LP#1982894

Don't reinstall nvidia packages on nvidia_apt_key_urls change

---

reactive/containerd.py
tox.ini

* Prevents nvidia_sources config changes (or fresh installs) from an attempted fetch and install of apt sources

configure nvidia sources only if `containerd.nvidia.available`

---

.github/workflows/main.yaml
actions/upgrade-actions.py
reactive/containerd.py
tests/unit/test_containerd_reactive.py
tox.ini

on upgrade of the `cuda-dtrivers`, `nvidia-smi` no longer functions and provides an error which indicates a need for a reboot
This change bubbles out the reboot warning in `juju status` on the unit.

Add reboot warning if `nvidia-smi` fails.

---

.gitignore
.jujuignore
actions/upgrade-actions.py
build-resources.sh
layer.yaml
lib/charms/layer/containerd.py
metadata.yaml
reactive/containerd.py
tests/data/charm.yaml
tests/integration/test_containerd_integration.py

In preparation for the Charmed Kubernetes 1.26 release, the `containerd` deb from Canonical was pinned on to 1.5.9 on jammy, focal, and bionic. 
In order to have more current compatible binaries for 1.26 kubelet, [LP#1996534](https://bugs.launchpad.net/ubuntu/+source/containerd/+bug/1996534) was opened, but will not be available in time for the release of the charm.  For the initial ck-1.26 the containerd will come with a 1.6.10 release of containerd resource already attached to the charm which supports amd64 and arm64
The charm is being extended to support installing binaries from the upstream [project's releases](https://github.com/containerd/containerd/releases).  A user can download the github release (say 1.6.10) for the target architecture of their cluster and attach it to the charm …

containerd resource binaries

---

build-resources.sh
tox.ini

Requires rebuild of docker-registry charm after merging the following:
* https://github.com/canonical/docker-registry-charm/pull/66

backup containerd release to 1.6.8

---

lib/charms/layer/containerd.py
reactive/containerd.py
templates/config.toml
templates/config_v2.toml
tests/unit/test_containerd_lib.py
tests/unit/test_containerd_reactive.py

[lp#2002593](https://bugs.launchpad.net/charm-containerd/+bug/2002593)
Eliminate warnings in /var/log/syslog which create 230k lines per day under certain conditions
```
cgroup v2 not implemented for Stats: not implemented
```

[LP#2002593] detect presence of cgroup2, and apply to containerd config if available

---

.github/workflows/main.yaml
reactive/containerd.py
tests/integration/test_containerd_integration.py

[LP#2017175](https://bugs.launchpad.net/charm-containerd/+bug/2017175)
to prevent extra gnome packages
[without this flag](https://paste.ubuntu.com/p/YTm3c7cCGM/) - 21 gnome packages
[with the flag](https://paste.ubuntu.com/p/9TvRfkmnj7/)  - 9 gnome packages
[including policy-kit-1-gnome](https://paste.ubuntu.com/p/fyKS4HxSVC/) - 0 gnome packages

install nvidia-drivers with `--no-install-recommends` option

---

config.yaml
tests/unit/test_containerd_reactive.py

Fixes: [LP#2034080](https://launchpad.net/bugs/2034080)
Per the [1.14.0 release notes](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/release-notes.html#fixes-and-features), deb packages for all supported distributions will be distributed via a singular "deb" repo.

Update libnvidia-container apt repo url

---

reactive/containerd.py

After a reboot, the `nvidia-smi` package will function, but nothing clears the flag indicating it needs a reboot.  Let's keep testing that this is broken until the `nvidia-smi` application no longer fails

[LP#1991010] Test that the reboot is necessary until the smi functions
